version: '2.4'
services:
  db:
    image: postgres
    container_name: loja
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lojaOnline
    ports:
      - "5432:5432"
    volumes:
      - loja_data:/var/lib/postgresql/data

volumes:
  loja_data: